src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/search', to: 'pages#search', as: 'search_page'

  resources :mentors
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[index show]
  resources :personal_messages, only: %i[new create]
  resources :conversations, only: %i[index show]
  resources :profiles
  resources :mentorships

  root to: 'pages#welcome'
end

src/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'

  has_many :personal_messages, dependent: :destroy

  has_one :profile, dependent: :destroy

  has_one :mentor, dependent: :destroy

  has_many :mentorships
  has_many :mentor_users, through: :mentorships

  has_many :menteeships, class_name: 'Mentorship', foreign_key: 'mentor_user_id'
  has_many :mentee_users, through: :menteeships, source: :user

  def username
    email.split('@')[0]
  end

  def get_name
    profile ? profile.name : username
  end
  
  def get_profile_field(field)
    profile ? profile[field] : ''
  end
end

src/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

src/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

src/app/views/users/_user_link.html.erb
 <% if user.mentor && user.mentor.accept_mentee? %>
    <%= link_to user.get_name, mentor_path(user.mentor) %>
<% else %>
    <%= link_to user.get_name, user_path(user) %>
<% end %>

src/app/views/users/show.html.erb
<div class="container">
<h1> 
  <%= @user.get_name %></h1>

<p>
<i>
  – <%= @user.get_profile_field(:job_title) %>
  at
  <%= @user.get_profile_field(:employer) %>
  </i>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.get_profile_field(:city) %>, 
  <%= @user.get_profile_field(:state) %>
</p>

<p>
  <strong>Why I want a mentor:</strong>
  <%= @user.get_profile_field(:why_i_want_a_mentor) %>
</p>
</div>