src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/search', to: 'pages#search', as: 'search_page'

  resources :mentors
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[index show]
  resources :personal_messages, only: %i[new create]
  resources :conversations, only: %i[index show]
  resources :profiles
  resources :mentorships

  root to: 'pages#welcome'
end

src/app/models/mentor.rb
# frozen_string_literal: true

class Mentor < ApplicationRecord
  belongs_to :user

  has_one_attached :picture

  has_many :skills, dependent: :destroy

  has_many :beliefs, dependent: :destroy
end

src/app/controllers/mentors_controller.rb
# frozen_string_literal: true

class MentorsController < ApplicationController
  before_action :set_mentor, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  # GET /mentors
  # GET /mentors.json
  def index
    @mentors = Mentor.all
    @skills = Skill::SKILLS
    @beliefs = Belief::BELIEFS
    @filter = params['filter']

    if @filter.present?
      @filter_beliefs = params['filter']['beliefs']
      @filter_skills = params['filter']['skills']

      if @filter_beliefs.present? && @filter_skills.present?
        # Mentor filter by skills
        @mentors = Mentor.joins(:skills).joins(:beliefs).where('skills.name IN (?) AND beliefs.name IN (?)', params['filter']['skills'], params['filter']['beliefs']).distinct
      elsif @filter_beliefs.present?
        @mentors = Mentor.joins(:beliefs).where('beliefs.name IN (?)', params['filter']['beliefs']).distinct
      else
        @mentors = Mentor.joins(:skills).where('skills.name IN (?)', params['filter']['skills']).distinct
      end
    else
      # @search = :need_help
      @mentors = Mentor.all
    end
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
    @skills = @mentor.skills
    @beliefs = @mentor.beliefs
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit; end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)
    @mentor.picture.attach(params[:mentor][:picture])
    @mentor.user = current_user

    # iterate through parameters - array created by multi select
    params[:mentor][:skills].each do |skill|
      @mentor.skills.build(name: skill)
    end

    params[:mentor][:beliefs].each do |belief|
      @mentor.beliefs.build(name: belief)
    end

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    @mentor.skills.each(&:destroy)

    @mentor.beliefs.each(&:destroy)

    params[:mentor][:skills].each do |skill|
      @mentor.skills.build(name: skill)
    end
    params[:mentor][:beliefs].each do |belief|
      @mentor.beliefs.build(name: belief)
    end
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: 'Mentor profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_mentor
    @mentor = Mentor.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def mentor_params
    params.require(:mentor).permit(:user_id, :bio, :accept_mentee, :linkedIn, :website, :picture)
  end
end

src/app/helpers/mentors_helper.rb
# frozen_string_literal: true

module MentorsHelper
end

src/app/views/mentors/_form.html.erb
<%= simple_form_for(@mentor) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.hidden_field :user %>
    <%= f.label :bio  %>
    <%= f.text_area :bio %>
      <script>
          tinymce.init({
          selector: '#mentor_bio',
            plugins: 'image link tinymcespellchecker',
            toolbar: 'a11ycheck casechange checklist formatpainter permanentpen table',
            toolbar_drawer: 'floating',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
          });
      </script>
      <br/>
    <p>Select Accepting new mentees so your mentor profile will be visible for mentoring relationship requests. </p>
    <p>You can uncheck this box when you are unavailable to mentor so your profile won't be on display.</p>
    <%= f.input :accept_mentee, label: "Accepting new mentees?" %>
    <%= f.input :linkedIn %>
    <%= f.input :website %>
    <%= f.label :picture %>
    <%= f.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
    <hr>
    <p>In order to help prospective mentees find you, select up to four of your strongest professional skills.</p>
    <%= f.input :skills, collection: Skill::SKILLS, input_html: { multiple: true }, class: "chosen-select" %>
    <hr>
    <p>In order to help prospective mentees find you, select up to four of your strongest interests.</p>
    <%= f.input :beliefs, collection: Belief::BELIEFS, input_html: { multiple: true }, class: "chosen-select" %>
  </div>
    
  <div class="form-actions">
    <%= f.button :submit, class:'btn btn-primary' %>
  </div>
<% end %>

src/app/views/mentors/edit.html.erb
<div class="container">
<h1>Editing my Mentor Profile</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Show', @mentor %> |
<%= link_to 'Back', mentors_path %>
</div>

src/app/views/mentors/index.html.erb
<div class="container">
<h1 class="row">Available Mentors</h1>
<div class="row">
  <div class="col-3 side-filter">
  
    <form action="<%= mentors_path %>" method="GET">
      <h5>Filter Mentors by Skill(s)</h5>

      <% @skills.each do |skill| %>
        <input id="filter_skill_<%= skill[1] %>" name="filter[skills][]" type="checkbox" value="<%= skill[1] %>" />
        <label for="filter_skill_<%= skill[1] %>"><%= skill[0] %></label><br />
      <% end %>
      <h5>Filter Mentors by Belief(s)</h5>

      <% @beliefs.each do |belief| %>
        <input id="filter_belief_<%= belief[1] %>" name="filter[beliefs][]" type="checkbox" value="<%= belief[1] %>" />
        <label for="filter_belief_<%= belief[1] %>"><%= belief[0] %></label><br />
      <% end %>
      <input type="submit" value="Filter Mentors" class="btn btn-primary" />
      <%= link_to "Reset Filter", mentors_path, class: "btn btn-secondary" %>
    </form>
  
  </div>
 
  <div class="card-columns col-9 align-items-top">
    <% @mentors.each do |mentor| %>
        <% if mentor.accept_mentee? %>
          <div class="card text-center">

            <div class="row align-items-center justify">
              <%= image_tag mentor.picture, class:"rounded-circle", width: 70, height: 70 if mentor.picture.attached?  %>
              <div class="col-9">
                  <h3 class="card-title align-items-center"><strong><%= mentor.user.get_name %></strong></h3>
              </div>
            </div>

            <p class= "card-text"><i><%= mentor.user.get_profile_field(:job_title) %></i></p>
            <p class= "card-text"><%= mentor.bio.truncate(40)%></p>
            <p>
              <a href="<%= mentor.linkedIn %>" class="px-2 fa-lg" target="_blank"><i class="fab fa-linkedin-in"></i></a>
              <a href="<%= mentor.website %>" class="px-2 fa-lg" target="_blank"><i class="fas fa-laptop-code"></i></a>
            </p>
            <%= link_to 'See more', mentor, class:"btn btn-primary" %>   
          </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>

src/app/views/mentors/new.html.erb
<div class="container">
<% if user_signed_in? %>
    <% if !current_user.mentor%>
        <h1><%= "Mentor Profile"%></h1>

        <%= render 'form', mentor: @mentor %>

        <%= link_to 'Back', mentors_path %>
        
    <% else %>
        <h3>You already have a mentor profile</h3>
        <%= link_to 'Show my Mentor profile', mentor_path(current_user.mentor), class:'btn btn-primary col-3'  %>
        <%= link_to 'Edit my Mentor profile', edit_mentor_path(current_user.mentor), class:'btn btn-primary col-3'  %>
    <% end %>
<% else %>
    <%= link_to "Login to continue", new_user_session_path %>
<% end %>
</div>

src/app/views/mentors/show.html.erb
<div class="container">
  <div class="float-right">
    <%= image_tag @mentor.picture, class: 'profile-image', height:300 if @mentor.picture.attached? %>
  </div>

  <h1><%= @mentor.user.get_name %></h1>
<p>
<i>
  – <%= @mentor.user.get_profile_field(:job_title) %>
  at
  <%= @mentor.user.get_profile_field(:employer) %>
  </i>
</p>

<p>
  <strong>Location:</strong>
  <%= @mentor.user.get_profile_field(:city) %>, 
  <%= @mentor.user.get_profile_field(:state) %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @mentor.bio.html_safe %>
</p>

<p>
  <strong>Accept mentee:</strong>
  <%= @mentor.accept_mentee %>
</p>

<div>
  <strong> Skills:</strong>
  <%if @skills%>
    <%@skills.each do |skill|%>
      <% next unless skill.get_friendly_name %>
      <ul>
        <li><%= skill.get_friendly_name %></li>
      </ul>
    <%end%>
  <%end%>
 </div>

 <div>
 <p><strong> Beliefs:</strong></p>
 <%if @beliefs%>
   <%@beliefs.each do |belief|%>
   <% next unless belief.get_friendly_name %>
     <ul>
       <li><%= belief.get_friendly_name %></li>
     </ul>
   <%end%>
 <%end%>
 </div>


<ul style="list-style:none; padding-left:0">
  <% unless @mentor.linkedIn.empty? %>
    <li><a href="<%= @mentor.linkedIn %>" target="_blank">LinkedIn</a> </li>
  <% end %>
  <% unless @mentor.website.empty? %>
    <li><a href="<%= @mentor.website %>" target="_blank">Website</a></li>
  <% end %>
</ul>
<% if current_user %>
  <% if current_user.mentor == @mentor  %>
    <% if !current_user.profile %> 
      <p><i>We recommend completing your user profile so that your name, job title and location are visible to potential mentees.</i></p>
    <% end %>
    <%= link_to 'Edit Mentor Profile', edit_mentor_path(@mentor), class:'btn btn-primary'  %>
    <% if current_user.profile %>
      <%= link_to 'Edit User Profile', edit_profile_path(current_user), class:'btn btn-primary'  %>
    <% else %>
      <%= link_to 'Complete User Profile', new_profile_path(current_user), class:'btn btn-success'%>
    <% end %>
    <%= link_to 'Delete Mentor Profile', @mentor, method: :delete, data: { confirm: 'Are you sure you want to delete mentor profile?' }, class:'btn btn-danger' %>
  <% elsif !current_user.mentor_users.include?(@mentor.user) %>
      <%= link_to 'Request mentor match', mentorships_path(:mentor_user_id => @mentor.user), :method => :post, class:'btn btn-primary' %>
  <% end %>
<% else %>
  <%= link_to 'Login to request mentor', new_user_session_path, class:'btn btn-primary'%>
<% end %>
</div>
</div>
</div>