src/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '/search', to: 'pages#search', as: 'search_page'

  resources :mentors
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: %i[index show]
  resources :personal_messages, only: %i[new create]
  resources :conversations, only: %i[index show]
  resources :profiles
  resources :mentorships

  root to: 'pages#welcome'
end

src/app/views/shared/_menu.html.erb
  <div class="col bg-dark nav_btn">
    <p class="nav-item">  
        <% if current_user %>
          <%= link_to 'Find a Mentor', mentors_path, class:"btn btn-sm btn-dark" %>
          <%= link_to 'My Mentoring Relationships', mentorships_path, class:"btn btn-sm btn-dark" %>
            <% if current_user.mentor %>
              <%= link_to 'My Mentor Profile', mentor_path(current_user.mentor), class:"btn btn-sm btn-dark" %>
            <% else %>
              <%= link_to 'Become a Mentor', new_mentor_path, class:'btn btn-sm btn-dark' %>
            <% end %>
        <% end %>
    </p>
  </div>
    
<% flash.each do |key, value| %>
  <div>
    <%= value %>
  </div>
<% end %>

src/app/views/shared/_nav.html.erb
<div class="col bg-primary ">
  <div class="row topnav"> 
  
    <div class="col-3 search_bar">
      <%= form_tag(search_page_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search by name", class: "form-control" %>  
          <div class="input-group-btn">
            
            <%= button_tag "",  :class => 'btn btn-primary fas fa-search',:name => nil%>  
          </div>  
      </div>  
      <% end %>
    </div>
    
    <div class="col text-right nav_btn">    
      <p class="nav-item">  
        <%= link_to 'Home', root_path, class:"btn btn-primary"  %>
        |
        <% if user_signed_in? %>
          <%= current_user.get_name %>
          |
          <% if current_user.profile %>
            <%= link_to 'Edit User Profile', edit_profile_path(current_user.profile), class:"btn btn-primary" %>
          <% else %>
            <%= link_to 'Create User Profile', new_profile_path, class:"btn btn-primary" %>
          <% end %>
          |
          <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class:"btn btn-primary"%>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class:"btn btn-primary" %>
          |
          <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary"  %>
        <% end %>
      </p>
    </div>

  </div>
</div>